spring:
  application:
    name: msusuario

server:
  port: 0

  error:
   include-stacktrace: on_param

eureka:
  client:
    service-url:
      defaultZone: http://mseureka-user:mea-sueresurk@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

