spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #True p/ localizar os Ms
          lower-case-service-id: true #True p/ localizar por lower case
  security: #Configuração de segurança usando o KeyCloak Oauth2 - realms
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/mspeladarealm #Url do meu realm

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://mseureka-user:mea-sueresurk@localhost:8761/eureka


